name: Python application

on:
  push:
    branches: [ "main" ]

#permissions:
#  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      working-directory: ./GitHubAction
      run: |
        python -m pip install --upgrade pip
        pip install py-dactyl
        pip install python-dotenv==0.17.1
        pip install requests
    - name: Creating DotEnv
      working-directory: ./GitHubAction    
      run: |
        echo gamemanager_ptero_url=${{secrets.GAMEMANAGER_PTERO_URL}} >> ./.env
        echo client_api_key="${{secrets.CLIENT_API_KEY}}" >> ./.env
        echo commit_name="${{github.event.head_commit.message}}" >> ./.env
        cat .env
        ls -l
        ls -l ../
    - name: Executing stuffies
      working-directory: ./GitHubAction    
      run: |
        python3 GitHubPteroScript.py
        python3 webhook.py